# ./istiod/kustomization.yaml
helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istiod
  namespace: istio-system
  valuesFile: "./istiod.pdev.yaml"
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-ingressgateway
  namespace: istio-gateway
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-egresssgateway
  namespace: istio-gateway
  valuesFile: "./egress.pdev.yaml"

resources:
- sample-app