# ./istiod/kustomization.yaml
helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istiod
  namespace: istio-system
  valuesFile: "./istiod.pdev.yaml"
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-ingressgateway
  namespace: istio-gateway
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-lab2
  namespace: istio-gateway
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-lab3
  namespace: istio-gateway
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-egresssgateway
  namespace: istio-gateway
  valuesFile: "./egress.pdev.yaml"
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.5.3
  releaseName: my-cert-manager
  namespace: cert-manager


helmCharts:

- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.18.0-alpha.0
  releaseName: istiod-canary
  namespace: istio-system
  valuesInline:
    revision: canary
  valuesFile: "./istiod.pdev.yaml"



resources:
- sample-app