# ./istiod/kustomization.yaml
helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istiod
  namespace: istio-system
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-ingressgateway
  namespace: istio-system
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: 1.17.1
  releaseName: istio-egresssgateway
  namespace: istio-system